### ISSUE TITLE
RX-28 Servos

### ISSUE THREAD

**Issue by 2Guz** [ROBOTIS-GIT/DynamixelSDK#10]
Hi again, I have looked online and I think there is no Dynamixel Wizard for Linux. I am also using RX-28 servos.

I tried sudo su, and still got the same error. Also, I made sure that the slide witch is on RS485 and that the servos are properly powered with 12V, but still got the same error. I'm sorry, but I don't know how I should do number 4 from your response earlier?

Thank you (I'm not too sure whether you would of been able to see my comment since the issue is close, so I created a new issue)

**Comment by ROBOTIS-Leon** [comment]
If you've never used your Dynamixel since you bought, it must have been set as ID: 1, baudnum : 34 (baudrate at 57600) as a default setting.

Download [Roboplus](http://en.robotis.com/BlueAD/board.php?bbs_id=downloads&mode=view&bbs_no=1132559&page=1&key=&keyword=&sort=&scate=) and follow the guide which describes how to change Dynamixels settings using Dynamixel Wizard:

[http://support.robotis.com/en/](http://support.robotis.com/en/) - Software Help - RoboPlus - Dynamixel Wzard.
