### ISSUE TITLE
DynamixelSDK with Arbotix-M 

### ISSUE THREAD

**Issue by cverginis** [ROBOTIS-GIT/DynamixelSDK#30]
Hello,

I am using an ArbotiX-M controller to communicate with an MX-servos. Can I use the DynamixelSDK library to control the motors? I installed everything, however when I run the read_write.py example, I get the message "There is no status packet". (In the long-run, I would like to give torque commands to the motor - MX-68). 
Thank you.

Best Regards,
Chris

**Comment by ROBOTIS-Leon** [comment]
Hi, Mr. verginis.

To tell the conclusion at the first place, there's no solution that we have now to do it. 

I guess, one way which can probably make it possible is what described below:
DynamixelSDK was developed for USB2Dynamixel or kind of customized devices which converts the signal from USART to TTL or RS485 interface. So, if you have or can make some kind of firmware on your device that can act as the signal converter, you may use it. I thought this since you ran python example code. 

Or, if you want to use your board as a master device, putting your own arduino codes or stuffs, please refer core source of OpenCM IDE (support.robotis.com/en/ - Software Help - OpenCM IDE - Software Download), which is kind of Arduino IDE that can be used for ROBOTIS OpenCM. It has some codes for port control, packet control. 

Plus, ROBOTIS is going to produce the OpenCR board, which is able to be used with ROS-embedded and arduino-compatibles. It will accompany firmware source and it would be fully opened through ROBOTIS-GIT, so you may refer it to make your own firmware, too.
