### ISSUE TITLE
Dynamixel MX106T (2.0) - Current Control Mode Problem

### ISSUE THREAD

**Issue by yildize** [ROBOTIS-GIT/DynamixelSDK#312]
Hey there, I want to use Dynamixel MX106T in current control mode (via Matlab) but I have some issues. I have designed a full state feedback controller and it is working fine with the MATLAB-Simulink model, on the other hand, I don't see meaningful results on the real-life system. The motor doesn't seem to be following the given current values. But when I try to control the motor by position control mode, It is working quite fine.

Also, I have seen that when I use the position control mode for the system, the current values vary around 10 but when I give the value 10 (even 20) for the current control mode, the motor is not moving at all, even if there is no load on the motor.

So, these results possessed me to think, is there something that I am missing or I don't know about the current control mode? Maybe there is a setting or some parameters that I need to change. Because I am pretty sure that, the controller algorithm is working well.

I know it is not a very specific question but I tried to give a nutshell, hope you can help me. Thanks in advance.

**Comment by ROBOTIS-zerom** [comment]
Hi, yildize.
Under low current conditions, control may not be precise due to various factors such as friction.

In the current control mode, the goal current acts as the input of the current controller.
In the current-based position control mode, the goal current acts as a limiter for the output of the position controller. The output value of the limiter becomes the input value of the current controller.
Therefore, the goal current value in the current control mode and the current-based position control mode may operate differently even if the same value is input.

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
