### ISSUE TITLE
[3.5.4][MATLAB][UD2D][AX-12W] Issue: communication with Matlab failed loadlibrary

### ISSUE THREAD

**Issue by salvatoreNRIM** [ROBOTIS-GIT/DynamixelSDK#324]
I am using a Dynamixel AX-12W. I am using Matlab 2019a, and USB2Dynamixel and my issue is that I keep getting problem in loading the library in the read_write.m file, attached the error message. Does anybody know how to solve it? 
![Screenshot (12)](https://user-images.githubusercontent.com/46469676/61676739-0aa6fb00-ad38-11e9-901c-4dd64511a5e5.png)
Also, I followed the solution proposed here, but it did not work for me https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/161

**Comment by asheesh-2019** [comment]
facing similar issue with AX-18a.

I believe the issue to be in the dynamixelSDK file.

The dynamixelSDK master folder should contain 1 folder and 3 subfolder in " [DynamixelSDK folder]/c/include "

but it cotains only one foder and one subfolder.

issue still unresolved.

**Comment by johncgh22** [comment]
Hi @salvatoreNRIM and @asheesh-2019 

I belive this error is because MATLAB doesnt understand some of the commands in the SDK, so it **needs a compiler** in order to build the packages.

I use this compliler for MATLAB:
[https://la.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-compiler](url)
![imagen](https://user-images.githubusercontent.com/35506735/66102772-1ce3b780-e579-11e9-8cae-0c05978e04b8.png)

Try installing this addon from the link, or in the Add-Ons tab inside MATLAB and give it a try.

**Comment by asheesh-2019** [comment]
hi  @johncgh22 

I had installed this compiler previously.

But its not working.

**Comment by ROBOTIS-Will** [comment]
This issue thread will be closed as there isn't recent activity. Please feel free to reopen when necessary.
