### ISSUE TITLE
[3.7.0][Python][CM700-lin-101][MX-28] Issue : My motor doesn't work

### ISSUE THREAD

**Issue by srikanthsrnvs** [ROBOTIS-GIT/DynamixelSDK#338]
I am trying to use the example code located in /python/test/protocol1_0 to get the motor to move. Unfortunately, it does not work. My MX28's are connected to a CM700, and the CM700 is directly connected to my computer running OSX

I've been stuck on this for days, can someone provide help?

Thanks

- I'm using `DynamixelSDK ver. 3.5.4`
- I'm using `python` Language
- I'm using `Lin-101` serial converter
- [USB2Dynamixel] / [USB2Dynamixel2] or [OpenCM904] / [OpenCR] / [CM700s] / [CM500s] or other ROBOTIS product only
- I'm using `MX-28`

**Comment by ROBOTIS-zerom** [comment]
The CM-700 Controller is not serial converter.

The DYNAMIXEL SDK can be used on PCs such as desktops or laptops, as well as on tablets, and also on SBCs like Raspberry Pi and UpBoards. In addition, it can be used with embedded boards that support the Arduino IDE. DYNAMIXEL uses TTL and RS485 communication. In order to use computer and DYNAMIXEL, we recommend USB2DYNAMIXEL or U2D2 as interface device.

Check below link:
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/device_setup/

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
