### ISSUE TITLE
[3.5.4][Labview][USB2Dynamixel2][MX-28] Issue : Library doesn't inlcude header file.

### ISSUE THREAD

**Issue by abuzaa** [ROBOTIS-GIT/DynamixelSDK#344]
[https://drive.google.com/file/d/1qI6jXbvTTL7TAn__LB08sDgC0iUXmcqZ/view?usp=sharing](url)

**Comment by johncgh22** [comment]
Hi,

First, check the tutorial for adding the library into LabVIEW:
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/library_setup/labview_windows/#labview-windows
Here it shows you where are the .dll and .h files you need to build the functions.

I recommend upgrading your SDK, it helps with some problems with communication. Use the latest version, check it here:
https://github.com/ROBOTIS-GIT/DynamixelSDK/releases/tag/3.7.21

**Comment by abuzaa** [comment]
Hi @johncgh22 

Thank you for your resposne, but my problem is that I can't find the header file '.h' in the new SDK. Do you have any idea where it is in the zipped folder?
Thanks in advance.

**Comment by johncgh22** [comment]
Hi @abuzaa 

For the new SDK, the .h file is locate in this folder:
~~\DynamixelSDK-3.7.21\c\include\dynamixel_sdk
Dont look inside the labview folder in the SDK, since all of the fuctions are made in C, you need to look in the c folder. From there, LabVIEW takes the info and make the VI neccesary. I´ll attach a file for my specific case...

![imagen](https://user-images.githubusercontent.com/35506735/64589607-1fccfd00-d36b-11e9-8a51-7c8ba7c1c92d.png)

**Comment by ROBOTIS-zerom** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
