### ISSUE TITLE
Why there are no conflicts on the serial line when all the motor report the position simultaneously?

### ISSUE THREAD

**Issue by itfanr** [ROBOTIS-GIT/DynamixelSDK#364]
Hello everyone,

I made a 6-dof robot with dynamixel motors. I found that they communication with eath other thougth serial.

The developer can send a broadcast command to get all the positions of them, which called sync group read.

What confused me is that why we did not encounter conflicts when all the motor report their position simultaneously?

Thank you.

https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/302

http://www.robotis.us/dynamixel-xm430-w350-r/

**Comment by ROBOTIS-zerom** [comment]
Hi, itfanr.
When using sync read, each device respnds in the order of the ID conatained in the instruction packet. Therefore, if one device does not respond in the middle, all IDs do not respond after that.

**Comment by itfanr** [comment]
@ROBOTIS-zerom  Thank you for your reply. But as the instruction packet is a broadcast command, how does the motors know the list of ID or know eath other?

**Comment by ROBOTIS-zerom** [comment]
Because parameter interpretation is different depending on the type of instruction.

http://emanual.robotis.com/docs/en/dxl/protocol2/#sync-read
![image](https://user-images.githubusercontent.com/15886081/71858893-396f2d00-3130-11ea-8760-96bc24cb237a.png)

In the example:
![image](https://user-images.githubusercontent.com/15886081/71858824-fc0a9f80-312f-11ea-9559-cd62325d6903.png)

P5 is the first device ID, P6 is the second device ID.

**Comment by itfanr** [comment]
@ROBOTIS-zerom  Thank you. I will read the protocol carefully.
