### ISSUE TITLE
There is no status packet !

### ISSUE THREAD

**Issue by dkwtfid** [ROBOTIS-GIT/DynamixelSDK#517]
ISSUE TEMPLATE ver. 1.2.0

Please fill this template for more accurate and prompt support.

1. Which DYNAMIXEL SDK version do you use?
  No idea

2. Which programming language/tool do you use?
  I can't code :(

3. Which operating system do you use?
  Windows 10

3. Which USB serial converter do you use?
  OpenCR

4. Which DYNAMIXEL do you use?
   XM430-W210

5. Have you searched the issue from the closed issue threads?
yes

6. Please describe the issue in detail
I've been trying to set up waffle pi robot. Dynamixel won't move so i'm following this tutorial https://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/ and this one to set up Arduino https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#setup-dynamixels-for-turtlebot3
I've basically been walking in the dark since the begining of the set up process and can't find any way to move forward since There is no status packet issue Arduino

7. How can we reproduce the issue?
I'm so lost pls help

**Comment by ROBOTIS-Will** [comment]
Hi @dkwtfid 
Ok, let's see in which step you lost.
TurtleBot3 comes with preconfigured DYNAMIXEL module, but just to make sure that everything is setup correctly, I'll walk you through the DYNAMIXEL setup.
Let me know if you are lost in a specific step.

1. Install Arduino IDE on your Windows ([Follow this instruction](https://emanual.robotis.com/docs/en/parts/controller/opencr10/#install-on-windows))
2. Connect the micro USB to OpenCR and connect to the PC.
3. Run Arduino IDE and open examples from `File > Examples > TurtleBot3 > TurtleBot3_setup > turtlebot3_setup_motor`
  ![tb3_setup](https://user-images.githubusercontent.com/26239359/127078803-00ac7c76-070e-46b0-ad08-fdaa4a8f3bb4.gif)

4. Connect the 12V SMP to OpenCR and turn on the power
5. Upload the Arduino example to OpenCR. In Windows, you'll see something like `COM ##` for the port instead of `dev/ttyACM0`.
  ![tb3_setup2](https://user-images.githubusercontent.com/26239359/127079104-2603febb-a7af-4329-9456-a225e779f4dc.gif)

6. Open the terminal and connect ONLY ONE DYNAMIXEL at a time to setup. Repeat this step for left and right DYNAMIXEL.
  ![tb3_setup3](https://user-images.githubusercontent.com/26239359/127079253-c7c6d6be-0e1b-4294-a01e-a983c5b30674.gif)

7. Once DYNAMIXEL setup is completed and tested, recover the TurtleBot3 firmware as instructed in the eManual ([step 10](https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#setup-dynamixels-for-turtlebot3))

**Comment by dkwtfid** [comment]
Thank you so much!
