### ISSUE TITLE
Linux Set up

### ISSUE THREAD

**Issue by 2Guz** [ROBOTIS-GIT/DynamixelSDK#8]
I'm following the steps provided on this page, but I have reached a part that I'm stuck on. https://github.com/ROBOTIS-Leon/test2/wiki/3.2.2-Linux I navigated to the linux64 directory and typed the command "make" and received an error. I then typed "make clean" to try and fix the issue, but when I typed "make" again, the same error appeared. 

Here is the error I have: 
root@river-turtlesim:/home/christian/Downloads/DynamixelSDK-master/c/build/linux64# make
mkdir -p ./.objects/
gcc -O2 -O3 -DLINUX -D_GNU_SOURCE -Wall -c -I../../include -m64 -fPIC -g -c ../../src/dynamixel_sdk/group_bulk_read.c -o .objects/group_bulk_read.o
In file included from ../../include/dynamixel_sdk/group_bulk_read.h:43:0,
                 from ../../src/dynamixel_sdk/group_bulk_read.c:44:
../../include/dynamixel_sdk/robotis_def.h:42:29: error: conflicting types for ‘int8_t’
 typedef char                int8_t;
                             ^
In file included from /usr/include/stdlib.h:314:0,
                 from ../../src/dynamixel_sdk/group_bulk_read.c:43:
/usr/include/x86_64-linux-gnu/sys/types.h:194:1: note: previous declaration of ‘int8_t’ was here
 __intN_t (8, __QI__);
 ^
make: *** [.objects/group_bulk_read.o] Error 1
root@river-turtlesim:/home/christian/Downloads/DynamixelSDK-master/c/build/linux64# make cleanrm -f ./.objects/group_bulk_read.o ./.objects/group_bulk_write.o ./.objects/group_sync_read.o ./.objects/group_sync_write.o ./.objects/packet_handler.o ./.objects/port_handler.o ./.objects/protocol1_packet_handler.o ./.objects/protocol2_packet_handler.o ./.objects/port_handler_linux.o ./libdxl_x64_c.so
root@river-turtlesim:/home/christian/Downloads/DynamixelSDK-master/c/build/linux64# make
mkdir -p ./.objects/
gcc -O2 -O3 -DLINUX -D_GNU_SOURCE -Wall -c -I../../include -m64 -fPIC -g -c ../../src/dynamixel_sdk/group_bulk_read.c -o .objects/group_bulk_read.o
In file included from ../../include/dynamixel_sdk/group_bulk_read.h:43:0,
                 from ../../src/dynamixel_sdk/group_bulk_read.c:44:
../../include/dynamixel_sdk/robotis_def.h:42:29: error: conflicting types for ‘int8_t’
 typedef char                int8_t;
                             ^
In file included from /usr/include/stdlib.h:314:0,
                 from ../../src/dynamixel_sdk/group_bulk_read.c:43:
/usr/include/x86_64-linux-gnu/sys/types.h:194:1: note: previous declaration of ‘int8_t’ was here
 __intN_t (8, __QI__);
 ^
make: *** [.objects/group_bulk_read.o] Error 1
root@river-turtlesim:/home/christian/Downloads/DynamixelSDK-master/c/build/linux64#

**Comment by ROBOTIS-Leon** [comment]
Hi!
I'm so sorry for the inconvenience.
The main reason of what you said is that `intN_t` data types are already predefined in the linux platform, so the error was occurred by double definition on `robotis_def.h`. Hence, you can solve it by putting `#if defined(_WIN32) || defined(_WIN64)` and `#endif` near the type definition of `intN_t`s (just wrap three of them), like:

```cpp
#if defined(_WIN32) || defined(_WIN64)
typedef char                int8_t;
typedef short int           int16_t;
typedef int                 int32_t;
#endif
```
I thought that this had been updated in the `DynamixelSDK-master` but it wasn't. It was absolutely my fault. Besides, after solving that problem, you will face different kind of errors so do your work on different way.

I recommend you to use the source of `DynamixelSDK-develop` rather than `DynamixelSDK-master` for now. Kinds of problems in the code are solved (as I know), and I will merge the `DynamixelSDK-master` when my work is finished, so don't waste your time. 

Any other questions, don't hesitate to ask me.

Thank you
